[custom.watson]
command = """watson status -p"""
when = """ ! test "$(cat ~/.config/watson/state)" == "{}" """
symbol = "‚è≥"
format = "[ $symbol ($output)]($style)"
disabled = false
[battery]
disabled = true